default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails_prelaunch_signup_dev

test:
  <<: *default
  database: rails_prelaunch_signup_test

production:
  <<: *default
  database: rails_prelaunch_signup_prod